### ISSUE TITLE
Linux: 'npm' binary not found

### ISSUE THREAD

**Issue by dror-g** [KumologicaHQ/kumologica-support#1]
Deploy step executes npm binary using `/bin/npm`.
However, the executable binary is not always present at this precise location, i.e when using NVM node version manager, in which case it's available in `/home/<user>/.nvm/versions/node/v13.6.0/bin/npm`.

Perhaps it's best to remove the `/bin/` path and call npm using system $PATH.

(can be resolved temporarily by user creating a symlink in /bin/)

**Comment by dror-g** [comment]
Same applies to the `node` command

**Comment by bjq-dev** [comment]
We don't use explicit path to call npm. The lambda build command is simple npm call. We had similar issue on mac, looks like https://www.npmjs.com/package/fix-path doesn't fix it for linux. 
Fix to investigate.

**Comment by bjq-dev** [comment]
0.9.4 version released.

Note: for electron to pick up path with npm, the default alias should be set by calling:

```bash
nvm alias default {specific node version}
```
