### ISSUE TITLE
Support for FTP

### ISSUE THREAD

**Issue by sparkyrider** [KumologicaHQ/kumologica-support#10]
There is support for SFTP but it would be nice to have support for FTP supporting anonymous auth to enable our workflow. Weekly we need to run a lambda function to connect to a public FTP server with no auth and no ssl and upload the files to S3. Support for streaming the files would be ideal so that we can get around the 500mb /tmp limit

**Comment by sparkyrider** [comment]
Hey Kumologica Team :)

Is this something that could make it onto the release schedule? I understand that FTP by nature is insecure file transfer, however, the majority of Public records are stored on FTP and the only way for us to ingest them is to use the old FTP protocol with anonymous login. Not many govs support SFTP or even FTPS currently.

**Comment by ab73863** [comment]
Hi @sparkyrider ,

We have the FTP node made available on the "Add more nodes" two weeks back. Sorry we missed notifying you on the same. Please try and let us know your feedback.

**Comment by sparkyrider** [comment]
Oh, that's awesome! Thank you so much, I'll try it out! Kumologica is amazing!
