### ISSUE TITLE
AWS EFS Support for Larger File Ops

### ISSUE THREAD

**Issue by sparkyrider** [KumologicaHQ/kumologica-support#22]
AWS Supports Mounting an EFS file share to Lambda functions. Adding support for this on Kumologica could enable a lot of larger data workflows than currently supported with the /tmp limits and could help enable larger use of the SFTP node as well as #10 Support for FTP nodes (hopefully a future node).

**Comment by bjq-dev** [comment]
Mounting of EFS is now possible via kumologica cli. Cli is part of runtime, the easiest way to access it would be to install runtime globally (npm install -g) and then use kl command. Use "kl help" option to see details. This is especially helpful in ci/cd environments.

We are aware that documentation for cli is missing on out website, cli is still under intensive development with many new features being implemented and extended. 
We will update or documentation site and publish few articles about cli very soon.

**Comment by sparkyrider** [comment]
Oh, this is awesome news! Thank you so much!
