### ISSUE TITLE
Question: GCP/Roadmap

### ISSUE THREAD

**Issue by sparkyrider** [KumologicaHQ/kumologica-support#25]
Hey Kumologica Team!,

Is GCP Cloud Functions on the roadmap for a future release? I did try it by exporting it as a Serverless function, and that worked well. Just wanted to see if it was something that was on the roadmap for the future as I remember seeing it in some Marketing copy in the past. 

Kumologica is game-changing! Thanks for all you guys do!

**Comment by bjq-dev** [comment]
Hi sparkyrider,

GCP is definitely on the roadmap, as you mentioned we already made kumologica runtime executable on gcp.
We are focused on our saas platform kumohub at the moment, so gcp deployment will be completed some time in september, that would include ui and cli integration.

Is serverless your primary toolset for deployment? Are you using terraform?

Thanks for your kind words, we are glad kumologica is helping you.

**Comment by sparkyrider** [comment]
Is there any information available on Kumohub? 

Serverless primarily with Terraform yes :)

**Comment by sparkyrider** [comment]
Wanted to follow up on this. Is there any details on what KumoHub will look like? Will it be a PaaS for integration?

**Comment by jteso** [comment]
Hi @sparkyrider ,

Very soon we will be able to share more details about KumoHub, but for now we can say that yes, it will be an iFaaS platform (Integration Function as a Service) designed to run your functions (Kumologica Flows) and access to some of the typical building blocks that are required in traditional integrations. 

Thanks for your support!
