### ISSUE TITLE
need to use md5 but the js node cannot find it

### ISSUE THREAD

**Issue by kensowens** [KumologicaHQ/kumologica-support#29]
https://www.npmjs.com/package/md5

In the js node I am trying to use

var md5 = require('md5');
return md5(msg.payload);

I get an error message back Cannot find module 'md5'

How do I allow Kumologica to find this module?

**Comment by bjq-dev** [comment]
Please add this module to package.json in your project directory. If you want to test it locally you may also need to run npm install in project directory, otherwise designer will install and package it during deployment.

You should source control package.json together with flow file.
