### ISSUE TITLE
Kumologica Designer not opening

### ISSUE THREAD

**Issue by jamap** [KumologicaHQ/kumologica-support#35]
I just installed Kumologica Designer 2.1.6 and it´s not saving a project nor connecting to AWS default profile. 

Probably the errors are connected. 

![image](https://user-images.githubusercontent.com/13342332/153783037-a7aeaa88-1c28-40db-b0b2-90ef45f4ff62.png)

Other environment information: 

Kumologica Designer Version 2.1.6 for Windows

Processor	Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz   1.90 GHz
Installed RAM	8.00 GB (7.84 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎2/‎4/‎2022
OS build	19042.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0

npm version ==> 8.3.1
Node version => V16.14.10
AWS Cli Version ==> aws-cli/2.4.18 Python/3.8.8 Windows/10 exe/AMD64 prompt/off

BR´s

**Comment by bjq-dev** [comment]
Issue recreated, preparing fix

**Comment by jamap** [comment]
FYI...

I thought it would be a problem with windows OS. So I tried this on a personal MacAir. Same problem

![image](https://user-images.githubusercontent.com/13342332/153872511-670bf7b0-ba84-46b3-9798-9bfffed7a702.png)

Same version of NPM, AWS Cli and Kumologica Designer... 
MacOS: Monterey 12
HW: Intel i3 1,6Ghz - 8Gb RAM

BR's

**Comment by bjq-dev** [comment]
The designer 2.1.7 containing fix has been released. It is available from our website or can be downloaded from github releases. With the nature of this bug, the auto upgrade may not work.

Change log is available: 
https://github.com/KumologicaHQ/kumologica-designer-releases/releases/tag/v2.1.7

**Comment by jamap** [comment]
Thank You... It´s opening now.
