### ISSUE TITLE
Designer not recognizing AWS Profile

### ISSUE THREAD

**Issue by jamap** [KumologicaHQ/kumologica-support#36]
Hi guys...

I´m trying to deploy the Hello World to AWS without success. It´s not recognizing my AWS Profile. I believe it´s an error from my side when configuring the AWS Profile in **Designer 2.1.7**. 

Here is the screen shot from Designer: 

![image](https://user-images.githubusercontent.com/13342332/154100469-9c84dd03-7735-45b2-97c3-2456f946631a.png)

Here are the contents of config files: 

Kumologica Credentials File: 

// This file contains all your sensitive credential information
// about your cloud connections used by Kumologica Designer.
// For more information visit  https://docs.kumologica.com/settings
//
// Azure with terraform:
// using a Service Principal with a Client Secret follow:
// https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret

// Examples:
//
// [kumohub.default]
// username = your-username
// password = your-password
// subscription = kumohub-subscription-id

// [aws.development]
// profile = _**kumologica**_

//
// [azure.default]
// subscription_id = 00000000-0000-0000-0000-000000000000
// client_id = 00000000-0000-0000-0000-000000000000
// client_secret = 0000000000000000000000000000000
// tenant_id = 00000000-0000-0000-0000-000000000000
//

Kumologica Settings File (There is no proxy) : 

[proxy]
custom=false
host=
port=
authentication=false
username=
password=

AWS Config File

[default]
region = us-west-1
output = json

[**_kumologica_**]
region = us-west-1
output = json

AWS Credentials File

[default]
aws_access_key_id = <<ACCESS_KEY_ID_1>>
aws_secret_access_key = <<ACCESS_SECRET_ID_1>>

[**_kumologica_**]
aws_access_key_id = <<ACCESS_KEY_ID_1>>
aws_secret_access_key = <<ACCESS_SECRET_ID_1>>

**Comment by bjq-dev** [comment]
please uncomment the profile lines:

[aws.development]
profile = kumologica

**Comment by arbalacha** [comment]
Hi @jamap, For a quicker response on your queries\ clarifications you can connect us on our community channel [kumologica discord channel](https://discord.gg/HrTCY8zXxM) .

**Comment by jamap** [comment]
Sorry guys... Really sorry for something so dumb!

**Comment by bjq-dev** [comment]
No worries
