### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by sparkyrider** [KumologicaHQ/kumologica-support#4]
Is MySQL support in the pipeline? A lot of our flows require it with our ELT pipelines.

**Comment by bjq-dev** [comment]
Do you use MySQL standalone server or AWS RDS one?

**Comment by sparkyrider** [comment]
MySQL standalone for dev, RDS for prod. Aurora Serverless V2 will probably be an interesting option as well once it comes out of preview.

**Comment by bjq-dev** [comment]
The SQL Node has been released as a custom node. 
Please install it in your project from the designer - "Add more nodes" button in the bottom left corner.

**Comment by sparkyrider** [comment]
Awesome thank you so much!!
