### ISSUE TITLE
Data Mapper : No Match Found

### ISSUE THREAD

**Issue by sharmmoh1983** [KumologicaHQ/kumologica-support#6]
While using data mapper ,if  transformation  logic is resulting into no  output , payload gets lost for next node .
There should be some default payload available for the subsequent nodes

**Comment by ab73863** [comment]
The implementation for this is actually expected to raise an exception in case of "no match" instead of allowing the flow to progress with the payload with which it was working. 

Proposing:
Implementing the feature of raising error when no match found.

**Comment by ab73863** [comment]
Correction on the proposal :

Incase of JSONAta expression resolved as empty.

msg.payload = {}

**Comment by ab73863** [comment]
Fixed. Will be available on 2.1.1 release.
